### ISSUE TITLE
Base URL loses "spot" part

### ISSUE THREAD

**Issue by franktakes** [NLeSC/spot#143] opened 2018-01-31 10:27 UTC
After opening spot at http://nlesc.github.io/spot, the URL part "/spot" gets removed and URLs become like http://nlesc.github.io/analyze 
This may not directly hurt visible functionality as a lot goes via asynchronous requests, but it for example makes it impossible to open a new window.

**Comment by fdiblen** [comment] 2018-02-15 15:05
Duplicate of #64

**Closed by fdiblen** 2018-02-15 15:05 UTC
