### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by bstienen** [NLeSC/spot#72] opened 2017-03-10 14:58 UTC
On configuring a dataset or altering a facet on the Analyse page, going back to the previous page can be done with either the back button of the browser or by clicking the corresponding menu button in the menu on the left. I would like it more if there could be an arrow pointing left to the left of the page title (just as there would be in Android for example, consistent with material design: https://i.stack.imgur.com/qddYm.png).

**Comment by jiskattema** [comment] 2017-03-23 09:26
duplicate of #47

**Closed by jiskattema** 2017-03-23 09:26 UTC
